[openai]
api_key = "YOUR_OPENAI_API_KEY"

[huggingface]
translate_api_key = "YOUR_HUGGINGFACE_TRANSLATION_API_KEY"
<<<<<<< HEAD
tts_api_key = "YOUR_HUGGINGFACE_TTS_API_KEY"
=======
tts_api_key = "YOUR_HUGGINGFACE_TTS_API_KEY"
>>>>>>> 5c27f68be6642656299871457c6e770b1380a1c9
